version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: language_learning_db
    restart: unless-stopped
    ports:
      - "51214:5432"
    environment:
      POSTGRES_USER: password
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data:
